name: ArcGIS Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install additional dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libkrb5-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install arcgis library
      run: |
        pip install arcgis==1.8.3
